# Created by jacob.mendt@pikobytes.de on 26.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# Installs all backup scripts / jobs on the machine
---
  - name: Make sure the backup (data) directory exists
    file:
      path: "{{ backup.data_path }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    become: yes

  - name: Make sure the backup (scripts) directory exists
    file:
      path: "{{ backup.script_path }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    become: yes

  # Copy and enable backup script for the database
  - template:
      src: backup_database.sh.j2
      dest: "{{ backup.script_path }}/backup_database.sh"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "u=rwx,g=rwx,o=r"

  - name: Enable backup_database.sh as cronjob
    cron:
      name: "Backup database"
      minute: "10"
      hour: "0"
      job: "{{ backup.script_path }}/backup_database.sh"

  # Copy and enable cleanup script for the database
  - template:
      src: clear_tmp_files.sh.j2
      dest: "{{ service.root_path }}/clear_tmp_files.sh"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "u=rwx,g=rwx,o=r"

  - name: Enable clear_tmp_files.sh as cronjob
    cron:
      name: "Clean up tmp files"
      minute: "*/5"
      hour: "0"
      job: "{{ service.root_path }}/clear_tmp_files.sh"