# Created by jacob.mendt@pikobytes.de on 13.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# Installs the geo service on a system.
---
- hosts: all
  vars:
    certs:
      root: /etc/certs
      certificates:
        - name: kartenforum.slub-dresden.de
          cert: cert.pem
          chain: chain.pem
          key: cert-key.key
    apache2:
      admin_mail: info@pikobytes.de
      cert:
        cert: /etc/certs/kartenforum.slub-dresden.de/cert.pem
        chain: /etc/certs/kartenforum.slub-dresden.de/chain.pem
        key: /etc/certs/kartenforum.slub-dresden.de/cert-key.key
      vhosts:
        - geo.test.kartenforum.slub-dresden.de
        - sdvvk20testgeo.slub-dresden.de
    db:
      password: set_your_own_password
      name: vkdb
      user: vk20
      restore_database: False
      dump: vkdb-new.dump
    service:
      root_path: /opt/kartenforum_georeference
      git_repo:
        url: https://github.com/slub/kartenforum_georeference
        branch: main
      use_git_repo: True
      settings:
        global_permalink_resolver: http://digital.slub-dresden.de/
        template_links_tms:
          - https://tms-1.test.kartenforum.slub-dresden.de/{}
          - https://tms-2.test.kartenforum.slub-dresden.de/{}
        template_link_wms: https://wms.test.kartenforum.slub-dresden.de/map/{}
        template_link_wms_transform: https://wms-transform.test.kartenforum.slub-dresden.de/map/{}
        template_link_wcs: https://wcs.test.kartenforum.slub-dresden.de/map/{}
        template_link_thumbnail: https://thumbnail.test.kartenforum.slub-dresden.de/{}
        template_link_zoomify: https://zoomify.test.kartenforum.slub-dresden.de/{}/ImageProperties.xml
    search:
      domain: search.test.kartenforum.slub-dresden.de
      port: 443
      ssl: True
      username: elastic
      password: set_your_own_password
    storage:
      root_path: /srv/vk
      directories:
        image_root: /srv/vk/original
        geo_root: /srv/vk/georef
        tms_root: /srv/vk/tms
        tmp_root: /srv/vk/tmp
        mapfile_root: /srv/vk/map_services
        mapfile_tmp_root: /srv/vk/map_services_tmp
        mosaic_root: /srv/vk/mosaics
        daemon_tmp: /srv/vk/daemon_tmp
        thumbnail_root: /srv/vk/thumbnails
        zoomify_root: /srv/vk/zoomify
        upload_tmp: /srv/vk/upload_tmp
      check_permissions: False
    backup:
      data_path: /srv/vk/backup/data
      script_path: /srv/vk/backup/scripts
  roles:
    - postgresql
    - import-database
    - georeference
    - apache-http
    - backup