# Created by jacob.mendt@pikobytes.de on 13.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# Installs the geo service on a system.
---
- hosts: all
  vars:
    certs:
      root: /etc/certs
      certificates:
        - name: kartenforum.slub-dresden.de
          cert: cert.pem
          chain: chain.pem
          key: cert-key.key
    apache2:
      admin_mail: info@pikobytes.de
      cert:
        cert: /etc/certs/kartenforum.slub-dresden.de/cert.pem
        chain: /etc/certs/kartenforum.slub-dresden.de/chain.pem
        key: /etc/certs/kartenforum.slub-dresden.de/cert-key.key
      vhosts:
        - geo.kartenforum.slub-dresden.de
    db:
      password: set_your_own_password
      name: vkdb
      user: vk20
      host: localhost # used for the database connection
      port: 5432 # used for the database connection
      restore_database: False
      dump: vkdb-new.dump
    search:
      domain: search.kartenforum.slub-dresden.de
      port: 443
      ssl: True
      username: set_your_own_username
      password: set_your_own_password
    storage:
      root_path: /srv/vk
      directories:
        image_root: /srv/vk/original
        geo_root: /srv/vk/georef
        tms_root: /srv/vk/tms
        tmp_root: /srv/vk/tmp
        mapfile_root: /srv/vk/map_services
        mapfile_tmp_root: /srv/vk/map_services_tmp
        mosaic_root: /srv/vk/mosaics
        thumbnail_root: /srv/vk/thumbnails
        zoomify_root: /srv/vk/zoomify
        upload_tmp: /srv/vk/upload_tmp
      check_permissions: False
    service:
      docker_image_name: pikobyteshq/slub_kartenforum_georeference:latest
      root_path: /opt/kartenforum_georeference
      dev_mode: False
      dev_mode_secret:
      log_level: INFO
      templates:
        tms_urls:
          - "https://tms-1.kartenforum.slub-dresden.de/{}"
          - "https://tms-2.kartenforum.slub-dresden.de/{}"
        wms_url: "https://wms.kartenforum.slub-dresden.de/map/{}"
        wms_transform_url: "https://wms-transform.kartenforum.slub-dresden.de/map/{}"
        wcs_url: "https://wcs.kartenforum.slub-dresden.de/map/{}"
        thumbnail_url: "https://thumbnail.kartenforum.slub-dresden.de/{}"
        zoomify_url: "https://zoomify.kartenforum.slub-dresden.de/{}/ImageProperties.xml"
      typo3_url: https://kartenforum.slub-dresden.de
      sentry_dsn:
      sentry_environment: staging
    backup:
      data_path: /srv/vk/backup/data
      script_path: /srv/vk/backup/scripts
  roles:
    - postgresql
    - import-database
    - georeference
    - apache-http
    - backup